version: '3.8'



services:
  postgres:
    image: postgres:15-alpine
    container_name: book-management-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: book-management-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - book-network
    depends_on:
      - postgres

  backend:
    build:
      context: ./book-management-backend
    container_name: book-management-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./book-management-backend:/app
    networks:
      - book-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./book-management-frontend
    container_name: book-management-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./book-management-frontend:/app
    networks:
      - book-network
    depends_on:
      - backend

networks:
  book-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
